# Site settings
title: Raimon Lapuente
email: sayhi@raimonlapuente.com
description: "Raimon's professional website. Some blogs and contact information. All about iOS and some crypto and blockchain"
baseurl: ""
url: "http://raimonlapuente.com"
twitter_username: wolffan
github_username:  wolffan

# Build settings
markdown: kramdown
permalink: none
highlighter: rouge
timezone: Europe/London
encoding: utf-8
paginate: 10
paginate_path: "blog/page:num"

#external urls
lyst_web: http://lyst.com
