# Site settings
title: Raimon Lapuente
email: r.lapuente@gmail.com
description: "Description"
baseurl: ""
url: "http://raimonlapuente.com"
twitter_username: wolffan
github_username:  wolffan

# Build settings
markdown: kramdown
permalink: none
highlighter: pygments
timezone: Europe/London
encoding: utf-8
pygments: true
paginate: 10
paginate_path: "blog/page:num"
